import mongoose from 'mongoose';

// An in-app alert addressed to a single user, generated by platform events
// (new request, status change, new message, new review, task reminders).
const notificationSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  type: {
    type: String,
    enum: ['request', 'status', 'message', 'review', 'task', 'system'],
    default: 'system',
  },
  title: {
    type: String,
    required: true,
  },
  body: {
    type: String,
    default: '',
  },
  // Client-side route to open when the notification is clicked (e.g. /projects/<id>).
  link: {
    type: String,
    default: '',
  },
  read: {
    type: Boolean,
    default: false,
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
});

// Dropdown list: a user's notifications, newest first. This index serves both
// the `user` filter and the `createdAt` sort directly, so the limited fetch is
// a pure indexed range scan (no blocking in-memory sort).
notificationSchema.index({ user: 1, createdAt: -1 });
// Unread badge / mark-all: the { user, read } prefix serves the unread count
// (countDocuments) and updateMany as a covered index range — no collection scan.
notificationSchema.index({ user: 1, read: 1, createdAt: -1 });

const Notification = mongoose.model('Notification', notificationSchema);

export default Notification;
