import mongoose from 'mongoose';

// An in-app alert addressed to a single user, generated by platform events
// (new request, status change, new message, new review, task reminders).
const notificationSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  type: {
    type: String,
    enum: ['request', 'status', 'message', 'review', 'task', 'system'],
    default: 'system',
  },
  title: {
    type: String,
    required: true,
  },
  body: {
    type: String,
    default: '',
  },
  // Client-side route to open when the notification is clicked (e.g. /projects/<id>).
  link: {
    type: String,
    default: '',
  },
  read: {
    type: Boolean,
    default: false,
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
});

// The bell query: a user's notifications, newest first / unread count.
notificationSchema.index({ user: 1, read: 1, createdAt: -1 });

const Notification = mongoose.model('Notification', notificationSchema);

export default Notification;
